###########

- name: Crear directorio /tmp/Grupo
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant

- name: Crear archivo datos.txt desde template
  template:
    src: template_01.j2
    dest: /tmp/Grupo/datos.txt
    owner: vagrant
    mode: '0644'
